"""First

Revision ID: 19948e43df06
Revises: 26a308e42239
Create Date: 2022-08-03 20:30:38.125819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19948e43df06'
down_revision = '26a308e42239'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
