"""first

Revision ID: 8ab4ee67a82a
Revises: 
Create Date: 2022-08-05 18:08:24.919187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab4ee67a82a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index(op.f('ix_company_company_id'), 'company', ['company_id'], unique=True)
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_record_record_id'), 'record', ['record_id'], unique=True)
    op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('applicant', 'admin', 'hr', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=True)
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_name')
    )
    op.create_table('hr_email',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('email_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_hr_email_email_id'), 'hr_email', ['email_id'], unique=True)
    op.create_table('hr_user',
    sa.Column('hr_user_id', sa.Integer(), nullable=False),
    sa.Column('hr_name', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['hr_user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('hr_user_id'),
    sa.UniqueConstraint('hr_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('hr_record',
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('record_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['hr_id'], ['hr_user.hr_user_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.record_id'], ),
    sa.PrimaryKeyConstraint('hr_id')
    )
    op.create_table('user_record',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('record_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.record_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_record')
    op.drop_table('hr_record')
    op.drop_table('user')
    op.drop_table('hr_user')
    op.drop_index(op.f('ix_hr_email_email_id'), table_name='hr_email')
    op.drop_table('hr_email')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index(op.f('ix_record_record_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_company_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
